const ACTIONS = {
  //Items entities action types
  SET_DATA: "SET_DATA",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEMS: "CLEAR_ITEMS",
  ADD_ITEMS: "ADD_ITEMS",
  UPDATE_ITEM: "UPDATE_ITEM",

  //Items view action types
  SHOW_LOADER: "SHOW_LOADER", // need to delete
  FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
  FETCH_REQUEST_SUCCESSED: "FETCH_REQUEST_SUCCESSED",
  FETCH_REQUEST_FAILED: "FETCH_REQUEST_FAILED",
  NEW_INPUT_REQUEST: "NEW_INPUT_REQUEST",
  NEW_INPUT_REQUEST_SUCCESSED: "NEW_INPUT_REQUEST_SUCCESSED",
  NEW_INPUT_REQUEST_FAILED: "NEW_INPUT_REQUEST_FAILED",
  ITEM_REQUEST_ALREADY_HAVE: "ITEM_REQUEST_ALREADY_HAVE",
  TOGGLE_STATUS_REQUEST_SUCCESSED: "TOGGLE_STATUS_REQUEST_SUCCESSED",
  TOGGLE_STATUS_REQUEST_FAILED: "TOGGLE_STATUS_REQUEST_FAILED",
  UPDTAE_ITEM_TEXT_REQUEST_SUCCESSED: "UPDTAE_ITEM_TEXT_REQUEST_SUCCESSED",
  UPDTAE_ITEM_TEXT_REQUEST_FAILED: "UPDTAE_ITEM_TEXT_REQUEST_FAILED",
  REMOVE_ITEM_REQUEST_SUCCEESSED: "REMOVE_ITEM_REQUEST_SUCCEESSED",
  REMOVE_ITEM_REQUEST_FAILED: "REMOVE_ITEM_REQUEST_FAILED",
  CLEAR_ALL_ITEM_REQUEST_SUCCESS: "CLEAR_ALL_ITEM_REQUEST_SUCCESS",
  CLEAR_ALL_ITEM_REQUEST_FAILED: "CLEAR_ALL_ITEM_REQUEST_FAILED",

  HIDE_LOADER: "HIDE_LOADER",
  SHOW_TOAST: "SHOW_TOAST",
  HIDE_TOAST: "HIDE_TOAST",
  SET_TOAST: "SET_TOAST",
  SET_FILTER: "SET_FILTER",
  SET_SORT: "SET_SORT",
  SEARCH_KEY: "SEARCH_KEY",
  SET_INPUT: "SET_INPUT",
  INPUT_NOT_VALID: "INPUT_NOT_VALID",
};

export default ACTIONS;
