const ACTIONS = {
  //Items entities action types
  SET_DATA: "SET_DATA",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ITEMS: "REMOVE_ITEMS",
  ADD_ITEMS: "ADD_ITEMS",
  UPDATE_ITEM: "UPDATE_ITEM",

  //Items view action types
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
  SHOW_TOAST: "SHOW_TOAST",
  HIDE_TOAST: "HIDE_TOAST",
  SET_TOAST: "SET_TOAST",
  SET_FILTER: "SET_FILTER",
  SET_SORT: "SET_SORT",
  SEARCH_KEY: "SEARCH_KEY",
};

export default ACTIONS;
